stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/external
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/external
    - src/data/data_preprocessing.py
    outs:
    - data/interim
