stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/external
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/external
    - src/data/data_preprocessing.py
    outs:
    - data/interim
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/interim
    - src/features/feature_engineering.py
    outs:
    - data/processed
  model_training:
    cmd: python src/models/model_training.py
    deps:
    - data/processed
    - src/models/model_training.py
    params:
    - model_training.n_estimators
    - model_training.max_depth
    - model_training.learning_rate
    - model_training.subsample
    - model_training.colsample_bytree
    - model_training.min_child_weight
    - model_training.gamma
    - model_training.reg_alpha
    - model_training.reg_lambda
    outs:
    - artifacts/
  inference:
    cmd: python src/models/inference.py
    deps:
    - artifacts/
    - src/models/inference.py
    outs:
    - prediction.json
